### ISSUE TITLE
AGREE does not install on OSATE 2.11

### ISSUE THREAD

**Issue by ASH-SYSTEMS** [loonwerks/AGREE#124]
The AGREE component cannot be installed on OSATE 2.11 (Windows version). I have tried installing both from the Install Extension (/Install additional components) and from the AGREE Update Site (/Install new software).

The reported error when installing the "AGREE Annex for OSATE2" (version 2.9.1) is:
Cannot complete the install because one or more required items could not be found.
  Software being installed: AGREE Annex for OSATE2 2.9.1 (com.rockwellcollins.atc.agree.feature.feature.group 2.9.1)
  Missing requirement: AGREE Annex for OSATE2 2.9.1 (com.rockwellcollins.atc.agree.feature.feature.group 2.9.1) requires 'org.eclipse.equinox.p2.iu; org.osate.aadl2.instantiation [1.0.1,2.0.0)' but it could not be found

When using the update site, the reported error is:
Cannot complete the install because of a conflicting dependency.
  Software being installed: AGREE Annex for OSATE2 2.9.1 (com.rockwellcollins.atc.agree.feature.feature.group 2.9.1)
  Software currently installed: OSATE Graphical Editor 5.2.0.v20220503-1819 (org.osate.ge.feature.feature.group 5.2.0.v20220503-1819)
  Only one of the following can be installed at once: 
    Instance Plug-in 2.0.0.v20220331-1608 (org.osate.aadl2.instantiation 2.0.0.v20220331-1608)
    Instance Plug-in 1.2.0.v20211215-1435 (org.osate.aadl2.instantiation 1.2.0.v20211215-1435)
  Cannot satisfy dependency:
    From: AGREE Annex for OSATE2 2.9.1 (com.rockwellcollins.atc.agree.feature.feature.group 2.9.1)
    To: org.eclipse.equinox.p2.iu; org.osate.aadl2.instantiation [1.0.1,2.0.0)
  Cannot satisfy dependency:
    From: OSATE Graphical Editor 3.1.0.v20220404-1242 (org.osate.ge 3.1.0.v20220404-1242)
    To: osgi.bundle; org.osate.aadl2.instantiation [2.0.0,3.0.0)
  Cannot satisfy dependency:
    From: OSATE Graphical Editor 5.2.0.v20220503-1819 (org.osate.ge.feature.feature.group 5.2.0.v20220503-1819)
    To: org.eclipse.equinox.p2.iu; org.osate.ge [3.1.0.v20220404-1242,3.1.0.v20220404-1242]

**Comment by kfhoech** [comment]
There is not yet a release of AGREE that supports API updates in OSATE 2.11.

While we hope to make a release shortly, it depends on availability of personnel.  For the interim please use OSATE 2.10.2 with AGREE 2.9.1.

**Comment by kfhoech** [comment]
Fixed in ffa80b32bef0739876da09e691ffc68d54a728f3 and released in [2.10.0-RELEASE](https://github.com/loonwerks/AGREE/releases/tag/2.10.0-RELEASE)
