### ISSUE TITLE
Is agree now supported on the command line?

### ISSUE THREAD

**Issue by zhenli798** [loonwerks/AGREE#126]
I want to write a script to validate multiple AADL models using the command line and save the validation results elsewhere

**Comment by zhenli798** [comment]
Is okay？

**Comment by iamundson** [comment]
We have not yet implemented a headless option for AGREE, but anticipate doing so in 2024.

**Comment by zhenli798** [comment]
Well, thank you. Where can I get more examples about AADL with agree annex to learn?
