### ISSUE TITLE
User Guide Updates: assign and connection

### ISSUE THREAD

**Issue by jendavis** [loonwerks/AGREE#28]
Please add, or consider adding, sections to the AGREE User Guide to cover assign statements and AGREE connection statements.

**Comment by kfhoech** [comment]
Documentation of `assign` statements should be added.

However, `connection` statements are intended to handle the case where a fan-in, that is multiple outputs connected to a single input, is actually illegal AADL.  OSATE only recently added a check for this (OSATE issue [#2356](https://github.com/osate/osate2/issues/2356)) and issue #45 indicates that AGREE should add a similar warning.  While it is possible that models may process inputs conditionally, such logic is more clearly described in the assume-guarantee contract. 
Accordingly, the AGREE team views `connection` statements as superfluous.  It is likely that they will be removed from the next major version of the AGREE language.

One action that we should take, however, is to add a validator rule that marks use of the connection statement as deprecated.
