### ISSUE TITLE
Java Validator issue with floor()

### ISSUE THREAD

**Issue by bcbrusse** [loonwerks/AGREE#66]
There appears to be an issue with AGREE's java validator when using floor(). For example, when using the following code I see an error reporting "Argument of floor cast is of type 'real' but must be of type 'real'"
> 
package floor_test
public
	annex agree {**
		const foo : int = floor(1.0);
	**};
end floor_test;

It appears there is documentation in the latest AGREE Users Guide, but I was not aware of these functions.

**Comment by kfhoech** [comment]
Confirmed.  Validator is simply looking for the incorrect type.

**Comment by kfhoech** [comment]
Fixed on master in commit a09d1eb4e0e1176eb9f5ca53722fd89133948755.
